version: '3.7'
services:
  frontend:
    image: node:14.5.0-alpine
    ports:
      - '80:8080'
    volumes:
      - ./vue/store:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run serve"